### ISSUE TITLE
Needs to be updated to bevy 0.4 maybe?

### ISSUE THREAD

**Issue by kragil** [8bit-pudding/bevy-tetris#2]
cargo run
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Clink-arg=-fuse-ld=lld -Zshare-generics=y --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler

**Comment by 8bit-pudding** [comment]
Yup, it's still linked in the awesome-bevy list so at least I could make sure it's up to date. I should have a look at what's new one of these days either way ;) Will see to it sometime soon.

**Comment by 8bit-pudding** [comment]
I've updated to Bevy 0.4, but looking at this again I don't think that's going to solve your problem. The file `.cargo/config` uses nightly Rust options for Linux and Mac currently. If you want to build this project using stable Rust, use the commented line under `[target.x86_64-unknown-linux-gnu]` instead, like so:

```
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]
```
